service:
  name: techbook-aaa
#app: your-app-name
#tenant: your-tenant-name

environment:

custom: ${file(./.env.yml):${opt:stage, self:provider.stage}}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}

functions:
  crc:
    handler: functions/handler.crc
    events:
      - http:
          method: get
          path: api/webhook
    environment:
      TWITTER_CONSUMER_SECRET_KEY: ${self:custom.twitter.consumer_secret_key}
  webhook:
    handler: functions/handler.webhook
    events:
      - http:
          method: post
          path: api/webhook
